### ISSUE TITLE
Redirect to proper subroute when clicking a crumb

### ISSUE THREAD

**Issue by okputadora** [mathematicalthinking/vmt#145]
These are "crumbs"
![crumb](https://user-images.githubusercontent.com/22389103/52020291-c9d3d500-24be-11e9-916b-679a47344d98.png)
 
They let the user know where they are. Right now, if you click MyVMT it redirects to `/myVMT/courses`. The desired behavior is for it to redirect to `/myVMT/rooms` when you're on a room page, `/myVMT/activities` when you're on an activity page and `/myVMT/courses` when you're on a course page.

The place to change these redirects would be in the render methods of Containers/Room, Containers/Activity (Containers/Course already has the desired behavior.

If you're feeling ambitious you could also add some tests to /cypress/integration/navigation.js to confirm the changes you've made work.

**Comment by myles-painter** [comment]
Hi! I'd like to give this a try

**Comment by jyothisankarreddy** [comment]
I can try this

**Comment by okputadora** [comment]
@myles-painter go for it! Let us know if you need any help getting the project set up. I've just added a .env.example to the repo which you will need to get it up and running. 

@jyothisankarreddy we're going to give out tasks on a first-come first-served basis so let's let myles take this one. We will have more issues for first-timers soon.

**Comment by okputadora** [comment]
@myles-painter Just checking in on your progress? Do you need any help? I'm going to open this back up if you're no longer working on it.
