### ISSUE TITLE
Fix Jumpy CSS when expanding a content box

### ISSUE THREAD

**Issue by okputadora** [mathematicalthinking/vmt#156]
This is a "Content Box" 
![contentbox](https://user-images.githubusercontent.com/22389103/52353397-80264580-29fc-11e9-8fba-91f2b7967394.png)

You can toggle the information it displays by clicking the arrow on the right
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22389103/52353583-da270b00-29fc-11e9-90b7-e2460cac85b5.gif)

Notice when this clicked the title text "jumps" a bit causing a jarring user experience. It's actually hard to see in this GIF because the frame rate is low and it happens fast. You can kind of make it out on the first click but it is definitely noticeable to a real user. 

The relevant code to fix this is in `./client/src/Components/UI/ContentBox` 
It is probably a CSS issue related to flex-box.

**Comment by nic-og** [comment]
Hi, I'd like to handle this. Is that possible?

**Comment by okputadora** [comment]
@nic-og Yes! Go for it! Please let us know if you need help getting the project setup locally, we'll be happy to help.
