### ISSUE TITLE
Missing .env.example

### ISSUE THREAD

**Issue by tna76874** [mathematicalthinking/vmt#309]
Hi there,
I try to set up vmt on docker, starting from here https://github.com/mathematicalthinking/vmt/pull/302

Indeed there are some problems (as displayed in the issue). I wonder if they might be caused by the missing `.env.example` ?

Regards

**Comment by tna76874** [comment]
actually, I'm getting this error message:
```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Access-Control-Allow-Origin"
```

**Comment by anzook** [comment]
Greetings - A .env file will be added to the /docs directory once reviewed, however in the meantime please feel free to contact me directly for assistance setting up your environment. 

That error may relate to CORS, however it may be hard to tell if the environment is not configured.

**Comment by tna76874** [comment]
Hi,
thanks for your answer. Actually I build a docker image from this issue here https://github.com/mathematicalthinking/vmt/pull/302
(obviously there are some breaking things with this PR). Now I try to get this whole thing up and running via docker - which is mandatory for my setup)

The error occurs once I try to open a new workspace.
Regards

**Comment by tna76874** [comment]
I think I figured out what the problem is. If I replace

```if (process.env.NODE_ENV === 'development' || process.env.NODE_ENV === 'test') {
  allowedOrigins += ', http://localhost:3000';
}```

by
```allowedOrigins = 'http://localhost:3000';```

vmt works. But there must be a better solution to this. Anyone has an idea?
Regards

**Comment by anzook** [comment]
Recent updates have helped address this- throughout all envs, the local NODE_ENV is always 'development' and startup scripts edited accordingly.

However the .env files for client and server have been updated, so this will be closed when new templates are added.

**Comment by exidy80** [comment]
The .env.examples for client and server have been updated, so I'm closing this issue. Please note that for increased security, almost all environment variables for the client have been moved to server/.env. The server now provides these variables to the client at runtime.
