### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by okputadora** [mathematicalthinking/vmt#92]
* The entire notification system needs to be rethought. 
* Their should be a notification Schema 
```
notificationType: “grantedAccess, requestAccess, assignedNewRoom’
resourceType: ‘room’, ‘course’,
resourceId: ObjectId(room or course)
parentResource: (optional) objectID (course)
fromUser: user who initiated the notification (i.e. the person who requested access if ntfType = requestAccess)
toUser: the user who this notification should show up for. (i.e. the facilitators of the course/room if the ntfType = requestAccess)
isTrashed = Boolean
```
* The user should have ONE list of notifications (not seperate ones for rooms/courses
  * This will require refactoring all over the place...react → redux → backend
* Notifications should be live...is a websocket a reasonable way to do this?
  * This will require refactoring the way we connect to the socket when joining a room
  * All signed in users should be connected to a socket

**Comment by philipwisner** [comment]
https://github.com/vigzmv/webSocket-notifications
